// Add or edit a scenario here. "answer" is the zero-based index of its safest action.
const scenarios = [
{type:'TEXT MESSAGE',sender:'Parcel delivery',address:'+1 (202) 555-0142',title:'Your package is on hold',body:'We could not deliver your package because your address is incomplete. Pay a $1.40 redelivery fee within 2 hours or your package will be returned.',link:'parcel-redelivery.example/pay',context:'You ordered something recently, but this text does not include your order number.',choices:['Pay the small fee to release the package.','Open the retailer’s app yourself and check your order.','Reply with your full address.'],answer:1,lesson:'Check through a trusted channel.',clues:['An unexpected fee and a short deadline push you to act before checking.','Expecting a package does not prove this sender knows about your order.','Use the retailer’s app or a carrier website you already know—not the link in the message.']},
{type:'EMAIL',sender:'School Library',address:'library@school.example',title:'A reminder about your library book',body:'Hi Alex,\nThe book you borrowed is due Friday. You can return it at the library desk. If you have already returned it, no action is needed.\nThank you!',context:'You borrowed a book last week. This is the usual return date, and the message asks for no payment, password, or attachment download.',choices:['Return the book at the library desk as usual.','Reply with your school password to confirm your identity.','Report it solely because it arrived by email.'],answer:0,lesson:'Match the request to the context.',clues:['The message matches a real activity and asks for an ordinary offline action.','There is no need to send account information to return a book.','A familiar sender address alone is not proof. The action and context matter too.']},
{type:'DIRECT MESSAGE',sender:'Game Rewards Team',address:'@rewards_support_728',title:'You won 10,000 game coins!',body:'Your account was randomly selected! Sign in on our reward page to claim your coins. Offer expires in 10 minutes. Do not miss out!',link:'game-bonus.example/login',context:'You did not enter a giveaway. This account contacted you first.',choices:['Use the link and enter your gaming password.','Send the offer to friends so they can claim it too.','Report and block the account using the platform’s controls.'],answer:2,lesson:'Unexpected prizes can be credential traps.',clues:['A surprise prize plus a demand to sign in elsewhere is a warning sign.','The countdown pressures you to skip verification.','A logo, username, or polished page can be copied. Check promotions through the official game.']},
{type:'TEXT MESSAGE',sender:'Someone claiming to be Mom',address:'+1 (202) 555-0188',title:'New number. Need a favor.',body:'Hey, it’s Mom. My phone broke and I’m using a friend’s. I need you to buy $200 in gift cards and text me the codes. I’m in a meeting so don’t call. Please hurry.',context:'The number is not saved in your contacts.',choices:['Buy the gift cards because it sounds urgent.','Call Mom on her known number or contact another trusted family member.','Ask this number for a photo, then send the codes if it looks right.'],answer:1,lesson:'Verify identity independently.',clues:['An unfamiliar number, secrecy, and gift-card codes are a risky combination.','Photos and personal details can be copied or faked.','Use contact information you already had—not a number provided in the new message.']},
{type:'EMAIL',sender:'Account Security',address:'security@northbank-alerts.example',title:'Your account will be suspended',body:'We detected unusual activity. Confirm your username, password, and security code immediately to avoid permanent suspension.',link:'northbank-alerts.example/verify',context:'You have an account at Northbank, but you have not checked your bank app yet.',choices:['Open your bank’s app yourself, or call the number on your card.','Reply with the requested security code.','Click the link because the address includes the bank’s name.'],answer:0,lesson:'A bank name in a domain is not enough.',clues:['Brand words can appear in an unrelated domain.','Do not provide passwords or one-time codes in response to an unsolicited message.','Check for alerts through your known bank app or the phone number on your card.']},
{type:'APP NOTIFICATION',sender:'School Portal',address:'Inside the school app you opened yourself',title:'Your assignment has been graded',body:'Your science assignment has feedback. Open the Grades tab to view your teacher’s comments.',context:'You launched your usual school app. The assignment is one you submitted yesterday.',choices:['Send your password to your teacher before opening Grades.','Treat every notification as a scam.','Open the Grades tab inside the app.'],answer:2,lesson:'The channel changes the risk.',clues:['You reached the familiar app independently, and the notification matches recent work.','Opening a normal in-app tab does not require sharing your password.','Practice evaluating context instead of assuming everything is safe—or everything is a scam.']},
{type:'EMAIL',sender:'Remote Student Jobs',address:'hiring@student-work.example',title:'Earn $500 a week from home',body:'You’re hired—no interview needed! We’ll send a check to buy your equipment. Deposit it, keep $100, and send the remaining money to our approved supplier today.',context:'You did not apply to this company. They want you to send money before you have started work.',choices:['Deposit the check and transfer the money as soon as it appears.','Stop responding and verify the company through independently found contact information.','Send half the money first to reduce the risk.'],answer:1,lesson:'Available funds do not mean a check is genuine.',clues:['An unsolicited job with no interview deserves scrutiny.','A check can appear in your balance before the bank discovers that it is fraudulent.','Sending part of the money onward is the trap; do not forward it.']},
{type:'BROWSER POP-UP',sender:'Security Warning',address:'A warning displayed inside a webpage',title:'VIRUSES FOUND: CALL NOW',body:'Your device is infected! Do not close this window. Call our certified technician immediately and install our remote support tool.',context:'The warning appeared while browsing a website. It is not from a security app you opened.',choices:['Call the number and allow the technician to connect.','Download the suggested tool to remove the virus.','Close the page; if concerned, open your trusted security software yourself.'],answer:2,lesson:'A webpage warning is not a device diagnosis.',clues:['Alarmist language tries to turn fear into immediate action.','An unsolicited request for remote access can put your device and information at risk.','Avoid the pop-up’s number and downloads. Use your own trusted tools or support channel.']},
{type:'MARKETPLACE CHAT',sender:'Interested buyer',address:'New buyer account',title:'I sent extra by mistake',body:'I paid you $350 for your $50 headphones. See my payment screenshot! Please refund the extra $300 now. The payment will show up after you refund me.',context:'Your payment app shows no incoming payment.',choices:['Check your own payment account and do not send a refund for money you have not received.','Trust the screenshot and refund $300.','Give the buyer your login so they can fix the payment.'],answer:0,lesson:'Screenshots are not payment confirmation.',clues:['An image can be edited. Check your own account directly.','A demand to pay money to receive money is a warning sign.','Keep transactions within the marketplace’s supported process and never share your login.']},
{type:'TEXT MESSAGE',sender:'Community Center',address:'Your usual activity reminder thread',title:'Robotics club reminder',body:'Reminder: robotics club meets at 4 PM tomorrow in Room 2. Bring your project. Questions? Ask at the front desk when you arrive.',context:'You signed up for these reminders. The time and location match your registration, and no links or payments are requested.',choices:['Reply with your home address and birth date.','Attend as planned; check with the center through a known channel if unsure.','Assume all messages in a familiar thread are always safe.'],answer:1,lesson:'A reasonable action still needs no extra personal data.',clues:['The reminder matches an activity you registered for and asks for no sensitive information.','There is no reason to volunteer additional personal details.','Familiar threads are helpful context, not a guarantee about future messages.']}
];
let index=0, answers=[];
const app=document.getElementById('app');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score=()=>answers.reduce((n,a,i)=>n+(a===scenarios[i].answer?1:0),0);
function render(){
 if(index===scenarios.length){renderResults();return;}
 const s=scenarios[index],done=answers.length>index;
 app.innerHTML=`<div class="top"><div><span class="eyebrow">CASE ${String(index+1).padStart(2,'0')} / ${scenarios.length}</span><h1>What’s your next move?</h1><p>Read the message. Consider the context. Choose the safest action.</p></div><div class="score"><strong>${score()*100}</strong>POINTS</div></div><div class="progress" role="progressbar" aria-label="Cases completed" aria-valuenow="${answers.length}" aria-valuemin="0" aria-valuemax="${scenarios.length}"><span style="width:${answers.length/scenarios.length*100}%"></span></div><div class="grid"><article class="message"><div class="messagebar"><span>${s.type}</span><span>Simulation</span></div><div class="msgbody"><div class="sender">${escapeHTML(s.sender)}</div><div class="address">${escapeHTML(s.address)}</div><h2>${escapeHTML(s.title)}</h2><p>${escapeHTML(s.body)}</p>${s.link?`<span class="fake-link">${escapeHTML(s.link)}</span>`:''}<p class="context"><strong>Your context</strong><br>${escapeHTML(s.context)}</p></div></article><section class="choices" aria-label="Your decision"><h2>Make the call.</h2><p>No timer. Taking a moment is part of the skill.</p>${s.choices.map((c,i)=>`<button class="choice ${done&&i===s.answer?'correct':''} ${done&&i===answers[index]&&i!==s.answer?'wrong':''}" data-choice="${i}" ${done?'disabled':''}><span class="letter">${'ABC'[i]}</span><span>${escapeHTML(c)}</span></button>`).join('')}<div id="feedback" aria-live="polite">${done?feedback(s):''}</div></section></div>`;
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));
 const next=document.getElementById('next');if(next)next.onclick=advance;
}
function feedback(s){const correct=answers[index]===s.answer;return `<div class="feedback"><span class="eyebrow">${correct?'+100 POINTS · SAFER CHOICE':'LET’S UNPACK THAT'}</span><h3>${escapeHTML(s.lesson)}</h3><ul>${s.clues.map(c=>`<li>${escapeHTML(c)}</li>`).join('')}</ul><button class="primary" id="next">${index===scenarios.length-1?'See your results':'Next case →'}</button></div>`;}
function choose(choice){if(index>=scenarios.length||answers.length>index)throw new Error('No unanswered case is active.');if(!Number.isInteger(choice)||choice<0||choice>=scenarios[index].choices.length)throw new Error('Choose 0, 1, or 2.');answers.push(choice);render();document.getElementById('next').focus();return {correct:choice===scenarios[index].answer,points:score()*100,lesson:scenarios[index].lesson};}
function advance(){if(answers.length<=index||index>=scenarios.length)throw new Error('Answer the current case first.');index++;render();window.scrollTo({top:0,behavior:'instant'});const heading=app.querySelector('h1');heading.tabIndex=-1;heading.focus();return {caseNumber:index<scenarios.length?index+1:null,finished:index===scenarios.length};}
function restart(){index=0;answers=[];render();window.scrollTo({top:0,behavior:'instant'});return {caseNumber:1,points:0};}
function renderResults(){const n=score();app.innerHTML=`<section class="result"><span class="eyebrow">SESSION COMPLETE</span><h1>${n>=8?'You’re building a sharp eye.':'Every case is a chance to learn.'}</h1><div class="result-number">${n}<span class="muted"> / ${scenarios.length}</span></div><p>You chose the safest action in ${n} of ${scenarios.length} fictional situations. This is practice feedback, not a certification.</p><button class="primary" id="restart">Practice again ↻</button><div class="review"><h2>Your case notes</h2>${scenarios.map((s,i)=>`<details><summary>${answers[i]===s.answer?'✓':'↻'} ${escapeHTML(s.title)} — ${answers[i]===s.answer?'Safer choice':'Review'}</summary><p><strong>Your choice:</strong> ${escapeHTML(s.choices[answers[i]])}</p><p><strong>Safest action:</strong> ${escapeHTML(s.choices[s.answer])}</p><p>${escapeHTML(s.clues.join(' '))}</p></details>`).join('')}</div><p><strong>Keep this habit:</strong> Pause when a message creates pressure. Check the request through a channel you already trust. Keep passwords and verification codes private.</p><p class="sources">Learn more: <a href="https://consumer.ftc.gov/scams" target="_blank" rel="noopener noreferrer">FTC scam information</a> · <a href="https://www.cisa.gov/secure-our-world/recognize-and-report-phishing" target="_blank" rel="noopener noreferrer">Recognize phishing</a></p></section>`;document.getElementById('restart').onclick=restart;}
render();
// Optional browser-agent interface. These actions use exactly the same game state as the buttons.
if(document.modelContext?.registerTool){for(const tool of [
{name:'read_current_case',description:'Read the current simulated message and choices without revealing the answer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){const s=scenarios[index];return s?{caseNumber:index+1,sender:s.sender,body:s.body,context:s.context,link:s.link,choices:s.choices,answered:answers.length>index}:{finished:true,points:score()*100};}},
{name:'answer_current_case',description:'Submit a choice for the current case and reveal learning feedback.',inputSchema:{type:'object',properties:{choice:{type:'integer',minimum:0,maximum:2}},required:['choice'],additionalProperties:false},execute(input){return choose(input?.choice);}},
{name:'advance_to_next_case',description:'Move to the next case after answering, or show final results.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:advance}
]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
